# Generated by Django 3.2.6 on 2021-08-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assestsconfig',
            name='preview_images',
            field=models.BinaryField(),
        ),
    ]
