# Generated by Django 3.2.6 on 2021-08-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_assestsconfig_preview_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assestsconfig',
            name='preview_images',
            field=models.ImageField(upload_to=''),
        ),
    ]
